import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {!session ? (
          <>
            Not signed in <br />
            <button
              onClick={() =>
                signIn("credentials", {
                  email: "zeluizr@commente.me",
                  password: "1234567890",
                  callbackUrl: "http://localhost:3000",
                  redirect: false,
                })
              }
            >
              Sign in
            </button>
          </>
        ) : (
          <>
            Signed in as {session.user.email} <br />
            <button onClick={() => signOut()}>Sign out</button>
          </>
        )}
      </main>
    </>
  );
}
